Add discord to players DB table
qbcore-framework/qb-core pull request #1135
Opened 2024-07-20 20:57 UTC by Cocodrulo

## Description

Nowadays most servers using QBCore uses discord whitelist, so the player will have their discord linked to FiveM. To ease integration with webapges I think discord information in main qbcore database table (players) should be kept to easy locate characters linked to a player.

## Checklist

- [x] I have personally loaded this code into an updated qbcore project and checked all of its functionality.
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

2024-07-26 13:15 UTC, nick-perry14 requested changes
Not sure how necessary this is, but if you really want it merged you **have** to provide a schema update with the PR.

2024-07-26 13:15 UTC, nick-perry14 commented on server/player.lua
> +        MySQL.insert('INSERT INTO players (citizenid, cid, license, discord, name, money, charinfo, job, gang, position, metadata) VALUES (:citizenid, :cid, :license, :discord, :name, :money, :charin
Where is the corresponding Schema update?

2024-07-26 13:18 UTC, nick-perry14 commented on server/player.lua
> +        PlayerData.discord = PlayerData.discord or QBCore.Functions.GetIdentifier(source, 'discord'):sub(9)
Forgot to add.  What is this is null?  calling :sub on a null may cause an issue.  Requires testing.

2024-07-26 15:38 UTC, nick-perry14 requested changes

2024-07-26 15:38 UTC, nick-perry14 commented on qbcore.sql
> +  `discord` varchar(255) NOT NULL,
This can be null.

2024-07-26 16:07 UTC, Cocodrulo commented
Just updated, I dont really know if `QBCore.Functions.GetIdentifier` does retrieve null because if we follow the documentation of the function `GetPlayerIdentifierByType` and it is right, it always return a string so, the sub will happen in a string, but change it if the docs are not correct

2024-07-26 16:28 UTC, nick-perry14 commented
`QBCore.Functions.GetIdentifier` can very much return nil.

![image](https://github.com/user-attachments/assets/092d083b-76a2-41a9-a88d-27524d10e2e9)

2024-08-04 11:42 UTC, lioncommunity-es commented
You will be correct if you are talking about old qbcore, now it uses the native: 

https://github.com/qbcore-framework/qb-core/blob/e488cbe61e661dc86d16d9e9e7ed4b3e1e341cea/server/functions.lua#L24

2024-08-04 11:44 UTC, Cocodrulo commented
You will be correct if you are talking about old qbcore, now it uses the native:

https://github.com/qbcore-framework/qb-core/blob/e488cbe61e661dc86d16d9e9e7ed4b3e1e341cea/server/functions.lua#L24-27

2024-09-08 03:02 UTC, Irishstevie commented
Maybe add something to the config.lua to turn this on and off

2024-09-08 15:26 UTC, Cocodrulo commented
Well, because the SQL file was change, I feel that it shouldn't be optional

2024-11-11 17:03 UTC, Cocodrulo commented
What about this?

2024-11-12 22:41 UTC, Qwerty1Verified commented
Could you possibly elaborate on the use case example you mentioned?

2024-11-12 22:48 UTC, Cocodrulo commented
> Could you possibly elaborate on the use case example you mentioned?

Yes, for example if u want to get have an admin menu to see all players data (no matters they are online or not) it is always easier, mostly for RP servers, to locate players based on discord Id.

Also if u want to integrate your sv with a discord bot or maybe a Webpage with discord login this will be helpful.

Discord is the main way gaming communities get along right now, and a better integration with this programme providing more critical data storing can become handy.

2024-11-13 22:10 UTC, GhzGarage commented
The idea is fine but needs more thought instead of just saving additional information

2024-11-13 22:24 UTC, Cocodrulo commented
As I said before, is not only for just saving data, is for future scripts functionality and for easier Web integration

2024-12-21 02:05 UTC, RojinxChhetri commented
> I think it really should be added. This will allow new scripts with new innovations

I agree that this addition is essential. It opens the door for creators to develop innovative scripts and introduces opportunities for further enhancements. It would be a valuable contribution to the project.

2024-12-21 02:06 UTC, RojinxChhetri approved these changes

2025-06-22 20:16 UTC, closed without merging