LSPD and ems offical rank from wiki
qbcore-framework/qb-core pull request #248
Opened 2021-10-03 18:44 UTC by evanillaa

**Describe Pull request**
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
- Does your code fit the style guidelines? [yes/no]
- Does your PR fit the contribution guidelines? [yes/no]

2021-10-03 19:56 UTC, Eralpozcan requested changes
isboss should be, Chief of Police

2021-10-03 20:25 UTC, evanillaa commented
@Eralpozcan done

2021-10-03 22:27 UTC, Eralpozcan requested changes
Please check "}," and space beetween, in police Readability is bad.

2021-10-04 00:12 UTC, Newtonzz requested changes
Please check your committed changes as they have minor errors that need fixing pointed out by Quarentin.

2021-10-04 00:12 UTC, Newtonzz commented on shared.lua
> +            },
Spotted by Quarentin, necessary to change or the PR won't be accepted.

2021-10-04 15:18 UTC, closed without merging