Add GetStreetLabel to core
qbcore-framework/qb-core pull request #394
Opened 2021-12-25 10:10 UTC by darknight2590

**Describe Pull request**

Add GetStreetLabel to core

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
- Does your code fit the style guidelines? [yes/no]
- Does your PR fit the contribution guidelines? [yes/no]

2021-12-25 22:13 UTC, xenfovn commented
i think get form coords is good

2021-12-27 20:56 UTC, Mojito-Fivem requested changes

2021-12-27 20:56 UTC, Mojito-Fivem commented on client/functions.lua
> +	local s1, s2 = GetStreetNameAtCoord(GetEntityCoords(PlayerPedId()).x, GetEntityCoords(PlayerPedId()).y, GetEntityCoords(PlayerPedId()).z)
Invoking the native this many times is probably not great

2021-12-27 20:56 UTC, Mojito-Fivem commented on client/functions.lua
> +QBCore.Functions.GetStreetLabel = function()
I think having the options to have a coords parameter would make this more versatile and you can default to the player's coords if it is not specified

2021-12-31 14:11 UTC, evanillaa approved these changes

2022-01-07 01:44 UTC, closed without merging