attachProp function
qbcore-framework/qb-core pull request #396
Opened 2021-12-25 10:47 UTC by darknight2590

**Describe Pull request**

attachProp function

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
- Does your code fit the style guidelines? [yes/no]
- Does your PR fit the contribution guidelines? [yes/no]

2021-12-27 20:54 UTC, Mojito-Fivem requested changes

2021-12-27 20:54 UTC, Mojito-Fivem commented on client/functions.lua
> +function QBCore.Functions.attachProp(ped, model, boneId, x, y, z, xR, yR, zR, Vertex)
This doesn't match the naming conventions and it upsets me, please change to AttachProp

2021-12-28 07:12 UTC, darknight2590 commented
@Mojito-Fivem done change

2022-01-01 12:01 UTC, evanillaa approved these changes

2022-01-07 01:55 UTC, merged