Spawning vehicles through the server
qbcore-framework/qb-core pull request #473
Opened 2022-01-12 09:04 UTC by darknight2590

In writing these posts, I relied on Spawning A Vehicle At A Distance in discord server
The following notes through the words of Mr.Kakarot

This will spawn the entity and callback the entity id which you can then use on the client side to check if the entity exists. It will NOT exist until a client(player) gets within range of it! While a client is NOT in range, the server “owns” the entity. So whenever a client gets into infinity range it then takes ownership of that entity and can be used by them.

![9999](https://user-images.githubusercontent.com/87971656/149097037-60350cb2-a70e-4763-8596-8ae281ea96dd.png)

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

2022-01-13 09:48 UTC, Mojito-Fivem requested changes
Please, for the love of cheese, comment your code.

2022-01-13 09:48 UTC, Mojito-Fivem commented on server/functions.lua
> +    local model = (type(entity) == "number" and entity or GetHashKey(entity))
this is not a valid way of getting model hash from an entity, and if this is a spawn vehicle function - why are you using the entity handle as a parameter??

2022-01-13 09:48 UTC, Mojito-Fivem commented on server/functions.lua
> +        Wait(0)
this can be improved with promises

2022-01-13 09:48 UTC, Mojito-Fivem commented on server/functions.lua
> +    local heading = locations ~= nil and locations.w ~= nil and locations.w or GetEntityHeading(GetPlayerPed(source))
this `locations` variable could do with a better name

2022-01-13 09:48 UTC, Mojito-Fivem commented on server/functions.lua
> +        return vehicle
It would make more sense if you returned NETWORK ID and not Entity Handle

2022-01-13 11:06 UTC, darknight2590 commented
I wrote it with my own little experience I think you have a better idea that you can prepare better
I am writing it according to my ability to do it and everyone can participate in making it better

2022-01-13 11:46 UTC, Mojito-Fivem commented
I've requested changes to this PR, this isn't about me having better ideas - this is about maintaining qb-core to a high standard.

2022-02-19 06:52 UTC, IdrisDose commented
Process is being changed, thank you for this PR though.

2022-02-19 06:52 UTC, closed without merging