[Update] Stuff and Things - Fix Exploit
qbcore-framework/qb-core pull request #559
Opened 2022-03-03 06:05 UTC by ItsANoBrainer

- Update doors on teleport so they don't get stuck (requires my doorlock PR that creates a updateDoors() export
- Support for heading with TeleportToCoords event
- Support for teleporting to location name with /tp and a default file with locations to use
- Remove 'QBCore:Server:AddItem' event (requires PR to other resources that use it)
- Support for an array of items that do the same thing with QBCore.Functions.CreateUsableItem
- Player exists check before removing or adding permission
- Trigger OnPlayerUnload as a server side event too
- Player.Functions.GetMetaData function
- Added reason to money remove logs
- Set dirt level to 0 on /car vehicles

2022-03-03 06:23 UTC, IdrisDose requested changes

2022-03-03 06:23 UTC, IdrisDose commented on client/events.lua
> +    exports['qb-doorlock']:updateDoors()
To decouple the code from specific resources can you please make this broadcast a client event and then add the update doors event  within qb-doorlock.

2022-03-03 06:23 UTC, IdrisDose commented on client/events.lua
> +    exports['qb-doorlock']:updateDoors()
To decouple the code from specific resources can you please make this broadcast a client event and then add the update doors event  within qb-doorlock.

2022-03-03 06:23 UTC, IdrisDose commented on client/events.lua
> +    exports['qb-doorlock']:updateDoors()
To decouple the code from specific resources can you please make this broadcast a client event and then add the update doors event  within qb-doorlock.

2022-03-03 06:23 UTC, IdrisDose commented on server/events.lua
> +-- RegisterNetEvent('QBCore:Server:AddItem', function(itemName, amount, slot, info)
Might want to deprecate the event instead of blatant removal. See #442

2022-03-03 06:23 UTC, IdrisDose commented on server/functions.lua
>      if Player then
Please fix this

2022-03-03 07:21 UTC, ItsANoBrainer commented
@IdrisDose Finished current requested changes. Please verify the deprecation is what you wanted.

2022-03-06 10:20 UTC, IdrisDose commented
regarding [bb5ea4d](https://github.com/qbcore-framework/qb-core/pull/559/commits/bb5ea4d9929af7ec0c9170fdde77d2b224fe0bcc)

I was meaning the same way I've done it before #442 so it doesn't run the function just prints it in the server console.

2022-03-06 11:23 UTC, BerkieBb commented
This looks good but
> Update doors on teleport so they don't get stuck (requires my doorlock PR that creates an updateDoors event

This is more of a workaround than a fix, I would rather fix this issue in qb-doorlock instead of making resources that change your location require to call this event

2022-03-06 21:42 UTC, ItsANoBrainer commented
> This is more of a workaround than a fix, I would rather fix this issue in qb-doorlock instead of making resources that change your location require to call this event

Agreed

2022-03-17 21:25 UTC, IdrisDose commented
@ItsANoBrainer conflicterinos

2022-03-17 21:50 UTC, ItsANoBrainer commented
@IdrisDose Done

2022-03-17 22:13 UTC, mk3ext commented on server/commands.lua
> +    local src = source
This is unneeded `local src = source`

2022-03-17 22:14 UTC, mk3ext requested changes

2022-03-17 22:14 UTC, mk3ext commented on server/commands.lua
> +    local src = source
This is unneeded `local src = source`

2022-03-18 00:09 UTC, vBooya reviewed
the tp to locations just pops the Player not Online notification no errors

2022-03-18 01:17 UTC, ItsANoBrainer commented
> the tp to locations just pops the Player not Online notification no errors

@vBooya You did not pull it properly then, because I just setup a vanilla qb-core recipe from tx and had no issues. Try repulling.

2022-03-18 01:19 UTC, ItsANoBrainer commented on server/commands.lua
> +    local src = source
Done

2022-03-20 18:14 UTC, vBooya commented
hopefully someone else can confirm it works, i literally went over it twice and copy pasted so i didnt mess up any typing

2022-03-20 18:14 UTC, vBooya commented
@ItsANoBrainer

2022-03-22 19:39 UTC, JonasDev99 commented
![image](https://user-images.githubusercontent.com/25738474/159561293-a011b3e4-8a77-427f-ab4c-daf6b642e4aa.png)
One of my devs cannot load into the server. He has no character at all and this is the error message. There was another error before but I fixed it by adding the following: 
![image](https://user-images.githubusercontent.com/25738474/159561699-21c70776-c9d8-4486-952c-188fc1d887d7.png)
The issue is, that its trying to access PlayerData.job.name but PlayerData.job  / PlayerData.gang is nil.
![image](https://user-images.githubusercontent.com/25738474/159562085-4152a1a7-8eb0-4e32-a290-d39e1a5fa6b1.png)

2022-03-22 19:44 UTC, JonasDev99 commented
Nevermind, just saw it has been fixed

2022-07-10 07:14 UTC, BerkieBb requested changes

2022-07-10 07:14 UTC, BerkieBb commented on client/events.lua
> +    if h then SetEntityHeading(ped, h) end
```suggestion
    SetEntityHeading(ped, h or GetEntityHeading(ped))
```

2022-07-10 07:14 UTC, BerkieBb commented on server/events.lua
>      Player.Functions.RemoveItem(itemName, amount, slot)
Add the print here as well like you did for AddItem but make it an error instead

2022-07-10 07:14 UTC, BerkieBb commented on server/functions.lua
>      QBCore.UseableItems[item] = cb
Remove this line

2022-07-10 07:14 UTC, BerkieBb commented on server/functions.lua
> +        for _,i in ipairs(item) do
```suggestion
        for i = 1, #item do
```
This is faster

2022-07-10 07:14 UTC, BerkieBb commented
@ItsANoBrainer lets get this merged

2022-07-18 18:04 UTC, D4isDAVID requested changes

2022-07-18 18:07 UTC, BerkieBb commented on server/player.lua
> +        end
Just use `if not meta then return end` looks much better and stops `false` from going through as well

2022-07-18 18:07 UTC, BerkieBb commented on server/player.lua
> +        end
But this should be done before trying to use `lower()`

2022-07-18 18:09 UTC, D4isDAVID commented on server/events.lua
> +RegisterNetEvent('QBCore:Server:RemoveItem', function(itemName, amount, _)
```suggestion
RegisterNetEvent('QBCore:Server:RemoveItem', function(itemName, amount)
```
This can be removed

2022-07-18 18:09 UTC, D4isDAVID commented on server/events.lua
> +RegisterNetEvent('QBCore:Server:AddItem', function(itemName, amount, _, _)
```suggestion
RegisterNetEvent('QBCore:Server:AddItem', function(itemName, amount)
```
This can be removed

2022-07-18 18:09 UTC, D4isDAVID commented on server/events.lua
> +-- This event is exploitable and should not be used. Will be deprecated soon. function(itemName, amount, slot)
```suggestion
-- This event is exploitable and should not be used. It has been deprecated. function(itemName, amount, slot)
```
It _is_ deprecated

2022-07-18 18:09 UTC, D4isDAVID commented on server/events.lua
> +    print(string.format("%s triggered QBCore:Server:RemoveItem by ID %s for %s %s. This event is being deprecated because of exploitation. Adjust your events accordingly to do this server side with p
```suggestion
    print(string.format("%s triggered QBCore:Server:RemoveItem by ID %s for %s %s. This event is deprecated due to exploitation. Adjust your events accordingly to do this server side with player functions.", GetInvokingResource(), src, amount, itemName))
```
English can be improved here

2022-07-18 18:09 UTC, D4isDAVID commented on server/events.lua
> +    print(string.format("%s triggered QBCore:Server:AddItem by ID %s for %s %s. This event is being deprecated because of exploitation. Adjust your events accordingly to do this server side with play
```suggestion
    print(string.format("%s triggered QBCore:Server:AddItem by ID %s for %s %s. This event is deprecated due to exploitation. Adjust your events accordingly to do this server side with player functions.", GetInvokingResource(), src, amount, itemName))
```
English can be improved here

2022-07-18 18:13 UTC, BerkieBb commented on server/events.lua
> +-- This event is exploitable and should not be used. Will be deprecated soon. function(itemName, amount, slot)
Should add `Will be removed soon` instead

2022-07-18 18:13 UTC, BerkieBb commented on server/events.lua
> +    print(string.format("%s triggered QBCore:Server:RemoveItem by ID %s for %s %s. This event is being deprecated because of exploitation. Adjust your events accordingly to do this server side with p
`and will be removed soon` can be added as well

2022-07-18 18:24 UTC, D4isDAVID commented on server/player.lua
> +        end
Although wouldn't `type(meta) ~= 'string'` be better to stop anything other than strings going through?

2022-07-18 18:30 UTC, D4isDAVID commented on server/events.lua
> +-- This event is exploitable and should not be used. Will be deprecated soon. function(itemName, amount, slot)
> Should add `Will be removed soon` instead

Updated it, should be better like this

2022-07-18 18:31 UTC, D4isDAVID commented on server/events.lua
> +-- This event is exploitable and should not be used. It has been deprecated. function(itemName, amount, slot, info)
```suggestion
-- This event is exploitable and should not be used. It has been deprecated, and will be removed soon. function(itemName, amount, slot, info)
```

2022-07-18 18:35 UTC, D4isDAVID commented on server/player.lua
> +        end
Just `if type(meta) ~= 'string' then return end` is sufficient, no?

2022-07-18 18:55 UTC, BerkieBb commented on server/player.lua
> +        end
No because you don't want to send `nil` to `type` and a `not` check is faster than a function call

2022-07-23 20:55 UTC, BerkieBb commented on server/player.lua
> +        end
If you can remove the extra `return` from your suggestion, I can commit this

2022-07-23 21:06 UTC, BerkieBb commented
This failing check is literally bullshit

2022-07-23 21:06 UTC, BerkieBb commented
Nevermind

2022-07-23 21:07 UTC, BerkieBb requested changes

2022-07-23 21:07 UTC, BerkieBb commented on server/player.lua
> +            if amount > 100000 then
Remove this part of added code please

2022-07-24 08:37 UTC, D4isDAVID commented on server/player.lua
> +        end
> If you can remove the extra `return` from your suggestion, I can commit this

Sorry, I kinda don't understand where the extra `return` is

2022-07-24 09:21 UTC, BerkieBb commented on server/player.lua
> +        end
Nevermind, weird formatting on the phone

2022-07-24 09:22 UTC, D4isDAVID commented on server/player.lua
> +        end
Understandable

2022-07-24 09:22 UTC, BerkieBb commented on server/player.lua
> +            if amount > 100000 then
That'll resolve the linting issues

2022-08-18 11:22 UTC, BerkieBb approved these changes

2022-08-18 14:41 UTC, D4isDAVID approved these changes

2022-08-19 16:29 UTC, merged