PlayerData.job.isleo
qbcore-framework/qb-core pull request #617
Opened 2022-04-04 12:28 UTC by Lionh34rt

**Describe Pull request**
Talked to Idris about this briefly, this allows servers to easily make new LEO Jobs like SASP, SAPR and BCSO and allows to easily check if the player is an LEO by using PlayerData.job.isleo.

If your PR is to fix an issue mention that issue here
Feature, not a fix

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest) Yes
- Does your code fit the style guidelines? [yes/no] Yes
- Does your PR fit the contribution guidelines? [yes/no] Yes

2022-04-10 00:57 UTC, KingRyuShin commented
What is this for though ?
Can't we just add a check like any other job like : if (PlayerData.job = "police" or PlayerData.job = "SARP") then ...
It would do the same thing no ?

2022-04-10 10:05 UTC, Lionh34rt commented
> What is this for though ? Can't we just add a check like any other job like : if (PlayerData.job = "police" or PlayerData.job = "SARP") then ... It would do the same thing no ?

If jobs and scripts are reworked this way by using .isleo and .ismechanic and .isambulance, server owners can create new jobs for these factions without having to adjust scripts in the future. You would have to adjust every script every time you decide to make a new police department or a new mechanic job and hope you don't forget anything.

That said, it would require every script to be rewritten one time to implement the .isleo variable but afterwards you wouldn't have to touch it again. This would also allow foreign languages to have different names for their police jobs since the locales system show that QBCore wants an easy to setup framework for not only English speaking servers.

Do I think this is a good thing to implement for QBCore Framework?
- Unsure, but I've contacted Idris about it because I'm unsure what direction QBCore wants to head. I know a lot of servers would want to have a Sheriff job, a State Police job etc. in the future and having the possibility to split their jobs so it allows them to split their funds, employees, ...

2022-04-11 12:57 UTC, Kendro1996 commented
Hey man this is very cool can you give me a idea of what else scripts I need to edit to make this work sorry I'm very new to all this

2022-04-11 20:46 UTC, FjamZoo approved these changes
This would create a overall easier user experience as they can skip all the annoying small job checks and just use a variable within the jobs.

2022-04-20 00:35 UTC, ItsANoBrainer approved these changes
Big Brain idea, I approve. This beats what I did (having a shared function that all the scripts call).

2022-04-20 00:38 UTC, ItsANoBrainer commented
What do we think about changing it from isleo and adding a type entry to each job that can be indexed instead of isleo? That way if in the future people want to add more similar verisons (isambulance, ismechanic) they dont have to edit the player class in qb-core?

2022-04-20 08:11 UTC, Lionh34rt commented
> What do we think about changing it from isleo and adding a type entry to each job that can be indexed instead of isleo

Probably a better idea if you want to expand this for all the jobs and not just police.

2022-04-21 02:00 UTC, ItsANoBrainer commented on server/player.lua
> +    PlayerData.job.isleo = PlayerData.job.isleo or false
```suggestion
    PlayerData.job.type = PlayerData.job.type or 'none'
```

2022-04-21 02:07 UTC, ItsANoBrainer requested changes

2022-04-21 02:07 UTC, ItsANoBrainer commented on server/player.lua
> +    PlayerData.job.isleo = PlayerData.job.isleo or false
```suggestion
    PlayerData.job.type = PlayerData.job.type or 'none'
```

2022-04-21 02:07 UTC, ItsANoBrainer commented on server/player.lua
> +        self.PlayerData.job.isleo = QBCore.Shared.Jobs[job].isleo or false
```suggestion
        self.PlayerData.job.type = QBCore.Shared.Jobs[job].type or 'none'
```

2022-04-21 02:07 UTC, ItsANoBrainer commented on shared/jobs.lua
> +        isleo = true,
```suggestion
        type = "leo",
```

2022-04-21 11:52 UTC, Lionh34rt commented
@ItsANoBrainer do I have to do anything with these proposed changes or is that for the dev team?

I'm not so familiar with using github

2022-04-21 15:07 UTC, izMystic commented
you would commit to your branch with those changes

2022-04-22 20:03 UTC, ItsANoBrainer commented
@Lionh34rt On the github comment page here, you should have a "accept changes" or something button by my requested changes.

2022-04-29 12:30 UTC, BerkieBb approved these changes

2022-04-29 12:35 UTC, BerkieBb commented
Now Idris is left to review this

2022-04-30 04:23 UTC, xenfovn commented
good job , If you don't know what it's for, here's a sample :
old
`if PlayerData.job.name == 'police' or PlayerData.job.name == 'ambunce' or PlayerData.job.name == 'mechanic' then`
just use 
`if PlayerData.job.type == "leo" then' then`

2022-05-10 19:29 UTC, ItsANoBrainer approved these changes

2022-05-28 07:15 UTC, Kendro1996 commented
> cant seem to get armoury working can you spot what im doing wrong     

CreateThread(function ()
    Wait(1000)
    while true do
        local sleep = 1000
        if inAmoury and PlayerJob.type == "leo" then
            if onDuty then sleep = 5 end
            if IsControlJustReleased(0, 38) then
                TriggerEvent("qb-police:client:openArmoury")
            end
        else
            sleep = 1000
        end
        Wait(sleep)
    end
end)

2022-06-16 01:07 UTC, merged