Add wait on removing playerdata
qbcore-framework/qb-core pull request #720
Opened 2022-06-10 08:02 UTC by Kmack710

**Describe Pull request**
Without the wait you cant use that players data at all on any other playerDropped events. Making you unable to get players names or citizenids for logs this 10 second wait gives scripts enough time to get the players info and use it before its gone.

If your PR is to fix an issue mention that issue here
 - Cant use any player data on log out like check job to remove from duty or get their name/citizenId for any logs 
 
**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? Yes
- Does your code fit the style guidelines? Yes
- Does your PR fit the contribution guidelines? Yes

2022-06-10 21:42 UTC, uShifty approved these changes
Looks good to me, I have noticed this aswell

2022-06-10 21:45 UTC, uShifty commented
You will need to update your pull request to remove the trailing whitespaces on line 20 to ensure it passes the lint check

2022-06-12 20:26 UTC, FjamZoo commented
I would recommend using a TimeOut instead of a createthread + timer, cleaner code and better functionality.

2022-06-16 01:11 UTC, GhzGarage commented
![image](https://user-images.githubusercontent.com/57848836/173970395-19026865-bf0d-466c-93e8-db069d33f993.png)

2022-07-23 17:46 UTC, BerkieBb requested changes

2022-07-23 17:46 UTC, BerkieBb commented on server/events.lua
> +    CreateThread(function()
Change this to SetTimeout and remove the wait and add `10000` after the `end` that closes the function to specify the timeout

2022-08-20 10:30 UTC, closed without merging